import 'package:firebaseblocryze/features/home_page/utils/home_page_strings.dart';
import 'package:firebaseblocryze/repository/job_posts/models/job_post.dart';


const DUMMY_ALL_JOBS = const [
  JobPost(
    title: 'Cocktail Bartender',
    description: HomePageStrings.dummyJobDescription,
    city: 'Lisbon',
    imageUrl: 'https://www.theiwsr.com/wp-content/uploads/us-bartender-interviews-700x525px-600x450.jpg',
    hourRate: '12€ / h',
    isRemote: false,
    slotsAvailable: 2,
    languages: ['Portuguese, English'],
  ),
  JobPost(
    title: 'NightClub Security',
    description: HomePageStrings.dummyJobDescription,
    city: 'Porto',
    imageUrl: 'https://www.offdutyofficers.com/wp-content/uploads/2019/12/nightclub-security-guard.jpeg',
    hourRate: '30€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese'],
  ),
  JobPost(
    title: 'House Cleaner',
    description: HomePageStrings.dummyJobDescription,
    city: 'Chaves',
    imageUrl: 'https://www.spectrumpolicy.org/wp-content/uploads/2019/11/House-Cleaning.jpg',
    hourRate: '4€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese'],
  ),
  JobPost(
    title: 'Receptionist',
    description: HomePageStrings.dummyJobDescription,
    city: 'Lisbon, Alameda',
    imageUrl: 'https://livingconcrete.co.uk/wp-content/uploads/2019/08/Concrete-Reception-Desk-1.jpg',
    hourRate: '5€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese'],
  ),
  JobPost(
    title: 'Sous Chef',
    description: HomePageStrings.dummyJobDescription,
    city: 'Lisbon',
    imageUrl: 'https://www.masterclass.com/course-images/images/3443/original/1570215402-GR_cinematic_12x5.jpg?width=450&height=600&fit=cover&dpr=2',
    hourRate: '9€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese, English'],
  ),
  JobPost(
    title: 'Assistant Kitchen Porter',
    description: HomePageStrings.dummyJobDescription,
    city: 'Lisbon',
    imageUrl: 'https://evolvehospitality.co.uk/wp-content/uploads/2018/03/porter-resized.jpg',
    hourRate: '5€ / h',
    isRemote: false,
    slotsAvailable: 2,
    languages: ['Portuguese'],
  ),
  JobPost(
    title: 'Electro House DJ',
    description: HomePageStrings.dummyJobDescription,
    city: 'Lisbon',
    imageUrl: 'https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fblogs-images.forbes.com%2Fzackomalleygreenburg%2Ffiles%2F2017%2F08%2F0731_lb-dj-marshmello_1200x630.jpg',
    hourRate: '32€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese, English'],
  ),
];

const DUMMY_MY_JOBS = const [
  JobPost(
    title: 'Gardner',
    description: HomePageStrings.dummyJobDescription,
    city: 'Oeiras',
    imageUrl: 'https://cdn.images.express.co.uk/img/dynamic/13/590x/can-gardeners-work-during-lockdown-1266816.jpg?r=1586586455254',
    hourRate: '7€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Any'],
  ),
  JobPost(
    title: 'Guitar Player for Wedding',
    description: HomePageStrings.dummyJobDescription,
    city: 'Porto',
    imageUrl: 'https://i.cdn.newsbytesapp.com/images/l205_35321599026097.jpg',
    hourRate: '30€ / h',
    isRemote: false,
    slotsAvailable: 1,
    languages: ['Portuguese'],
  ),
];