name: firebaseblocryze
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  awesome_dialog: ^1.2.0
  cached_network_image: ^2.5.0
  carousel_slider: ^2.3.1
  dartz: ^0.9.1
  equatable: ^1.2.5
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  freezed_annotation: ^0.7.1
  firebase_storage: ^3.1.0+1
  flutter_bloc: ^6.0.1
  flushbar: ^1.10.4
  formz: ^0.3.2
  google_sign_in: ^4.5.1
  google_maps_flutter: ^1.0.3
  get_it: ^4.0.2
  injectable: ^1.0.5
  image_picker: ^0.6.7+11
  json_annotation: ^3.0.1
  mask_text_input_formatter: ^1.2.1
  url_launcher: ^5.7.8
  uuid: ^2.0.4
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.10.9
  lint: ^1.1.1
  injectable_generator: ^1.0.3
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/ryze-app-logo.jpg
     - assets/ryze-app-logo-circle.png
     - assets/no-image-placeholder.jpg
     - assets/onboarding-01.jpg
     - assets/onboarding-02.jpg
     - assets/payment-error-01.png
     - assets/google-logo.png
     - assets/ryze-placeholder-category.png
     - assets/ryze-calendar-icon.png
     - assets/creditcard/mastercard.png
     - assets/creditcard/contact_less.png
  # example:
  fonts:
    - family: CourrierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
