name: firebaseblocryze
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  equatable: ^1.2.5
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^6.0.1
  get_it: ^4.0.2
  injectable: ^1.0.5
  flushbar: ^1.10.4
  uuid: ^2.0.4
  carousel_slider: ^2.3.1
  json_annotation: ^3.0.1
  awesome_dialog: ^1.2.0
  image_picker: ^0.6.7+11
  google_maps_flutter: ^1.0.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.10.9
  lint: ^1.1.1
  injectable_generator: ^1.0.3
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/ryze-app-logo.jpg
     - assets/no-image-placeholder.jpg
     - assets/onboarding-01.jpg
     - assets/onboarding-02.jpg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
